apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cluster-proxy
  labels:
    app.kubernetes.io/name: redis-cluster-proxy
    helm.sh/chart: redis-cluster-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-cluster-proxy
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-cluster-proxy
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: proxy
          containerPort: {{ .Values.port }}
          protocol: TCP
        env:
        - name: CLUSTER_ADDRESS
          value: {{ .Values.cluster_address | quote }}
        - name: PORT
          value: {{ .Values.port | quote }}
