apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-proxy
  labels:
    app.kubernetes.io/name: redis-cluster-proxy
    helm.sh/chart: redis-cluster-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: proxy
  selector:
    app.kubernetes.io/name: redis-cluster-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
